catalog:
  '@cloudflare/vite-plugin': 1.11.7
  '@eslint/js': 9.34.0
  '@paralleldrive/cuid2': ^2.2.2
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-toggle': ^1.1.10
  '@tailwindcss/vite': ^4.1.12
  '@tanstack/config': ^0.20.0
  '@tanstack/eslint-plugin-query': ^5.83.1
  '@tanstack/eslint-plugin-router': ^1.131.2
  '@tanstack/react-devtools': ^0.4.6
  '@tanstack/react-query': ^5.85.5
  '@tanstack/react-query-devtools': ^5.85.5
  '@tanstack/react-router': ^1.131.27
  '@tanstack/react-router-devtools': ^1.131.27
  '@tanstack/router-plugin': ^1.131.27
  '@types/better-sqlite3': ^7.6.13
  '@types/node': 24.3.0
  '@types/react': 19.1.11
  '@types/react-dom': 19.1.7
  '@vitejs/plugin-react': 5.0.1
  '@vitest/ui': ^3.2.4
  better-auth: ^1.3.7
  better-sqlite3: ^12.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.2.1
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eslint: 9.34.0
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.20
  globals: 16.3.0
  hono: 4.9.4
  lucide-react: ^0.541.0
  prettier: ^3.6.2
  react: 19.1.1
  react-dom: 19.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.12
  tw-animate-css: ^1.3.7
  typescript: 5.9.2
  typescript-eslint: 8.40.0
  vite: ^7.1.3
  vitest: ^3.2.4
  wrangler: 4.32.0
  zod: ^4.1.1

catalogMode: strict

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - unrs-resolver
  - workerd
